FROM python:3.7-slim

#Docker is a container that works similar as an virtual environment, but as a guideline/instruction to run something

ARG BASIC_AUTH_USERNAME_ARG
ARG BASIC_AUTH_PASSWORD_ARG

ENV BASIC_AUTH_USERNAME=$BASIC_AUTH_USERNAME_ARG
ENV BASIC_AUTH_PASSWORD=$BASIC_AUTH_PASSWORD_ARG

COPY ./requirements.txt /usr/requirements.txt
WORKDIR /usr
RUN pip3 install -r requirements.txt

COPY ./src /usr/src
COPY ./models /usr/models
#COPY ./app/main.py /usr/app/main.py

ENTRYPOINT [ "python3" ]

CMD [ "src/app/main.py" ]